# Generated by Django 4.0.6 on 2022-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
