# Generated by Django 4.1 on 2022-08-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block1',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Menu Blocks Level 1',
            },
        ),
        migrations.CreateModel(
            name='Block2',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.CharField(max_length=30)),
                ('block1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block1')),
            ],
            options={
                'verbose_name_plural': 'Menu Blocks Level 2',
            },
        ),
        migrations.CreateModel(
            name='CardboxType',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('width', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cardbox Types',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('slug', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='DataPage',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pages',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(max_length=256)),
                ('block_1', models.CharField(max_length=256)),
                ('block_2', models.CharField(max_length=256)),
                ('menu', models.CharField(max_length=256)),
                ('notebook', models.FileField(upload_to='upload/')),
            ],
            options={
                'verbose_name_plural': 'Upload Files',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('slug', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizational Units',
            },
        ),
        migrations.CreateModel(
            name='Link3',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.CharField(max_length=30)),
                ('block2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block2')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'verbose_name_plural': 'Menu Links Level 3',
            },
        ),
        migrations.CreateModel(
            name='Link2',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.CharField(max_length=30)),
                ('block1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block1')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'verbose_name_plural': 'Menu Links Level 2',
            },
        ),
        migrations.CreateModel(
            name='Link1',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.CharField(max_length=30)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'verbose_name_plural': 'Menu Links Level 1',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organizationalunit'),
        ),
        migrations.CreateModel(
            name='Cardbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(default='400px', max_length=50)),
                ('notebook', models.CharField(max_length=1024)),
                ('scroll', models.BooleanField(default=False)),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cardboxtype')),
            ],
            options={
                'verbose_name_plural': 'Cardboxes',
            },
        ),
        migrations.AddField(
            model_name='block1',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard'),
        ),
    ]
