# Generated by Django 4.0.6 on 2022-08-12 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block1',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block2',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(max_length=30)),
                ('block1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardboxType',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('slug', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataPage',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('slug', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link3',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(max_length=30)),
                ('block2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block2')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link2',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(max_length=30)),
                ('block1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.block1')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link1',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(max_length=30)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organizationalunit'),
        ),
        migrations.CreateModel(
            name='Cardbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.IntegerField(default=400)),
                ('notebook', models.CharField(max_length=1024)),
                ('data_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datapage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cardboxtype')),
            ],
        ),
        migrations.AddField(
            model_name='block1',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard'),
        ),
    ]
