# Generated by Django 4.1 on 2022-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook', models.CharField(max_length=1024)),
                ('cron', models.CharField(max_length=50)),
                ('next_run', models.DateTimeField(default=None, null=True)),
                ('html_file', models.CharField(default=None, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Schedulers',
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('notebook',), name='ux_schedule_notebook'),
        ),
    ]
